name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    container:
      image: alpine-edge
    steps:
      - uses: actions/checkout@v1
      # Set up any tools and build steps here
      # This example uses a Node.js toolchain to build a site
      - name: Install and Run Zola
        run: |
          apk add zola --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
          zola build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
